export const FETCH_USER = 'FETCH_USER';

export const FETCH_MATCH = 'FETCH_MATCH';
export const FETCH_MATCHES = 'FETCH_MATCHES';
export const FETCH_MATCHES_LOADING = 'FETCH_MATCHES_LOADING';

export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYERS_LOADING = 'FETCH_PLAYERS_LOADING';

export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAMS_LOADING = 'FETCH_TEAMS_LOADING';

export const SET_ADMIN = 'SET_ADMIN';
export const SET_TOAST = 'SET_TOAST';
export const SET_TOP_GOALSCORERS = 'SET_TOP_GOALSCORERS';
